include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**
  errors:
    invalid_dependency: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - use_super_parameters
